name: forfor
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.25.0-8.1.pre"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.7
  flutter_svg: 0.20.0-nullsafety.3
  font_awesome_flutter: ^8.5.0
  flutter_signin_button: ^1.1.0 
  kakao_flutter_sdk: ^0.6.4
  dio: 
  json_annotation: 
  platform:  
  package_info:
  email_auth: ^0.0.1+1.9
  country_list_pick: ^1.0.1+4
  flutter_cupertino_date_picker: ^1.0.26+2
  gender_picker: ^1.1.0
  image_picker: ^0.8.1+3
  multi_image_picker2: ^5.0.2
  flutter_absolute_path: ^1.0.6
  email_validator: ^2.0.1
  navigation_rail: ^1.5.0
  firebase_auth: ^3.1.4
  google_sign_in: 
  cloud_firestore: 
  firebase_core: 
  firebase_storage: 
  cloud_functions: 
  flutter_web_auth: ^0.3.0
  uuid: ^3.0.4
  multi_select_item: ^1.0.3
  flutter_reaction_button: ^1.0.8
  collapsible_sidebar: ^2.0.1
  validators: ^3.0.0
  url_launcher: ^6.0.9
  http:
  permission_handler: 
  google_fonts: ^2.1.0
  get: ^4.3.6
  flutter_slider_drawer: ^2.0.0
  custom_radio_grouped_button: ^2.0.0
  intrinsic_grid_view: ^0.0.2
  bubble: ^1.2.1
  hidden_drawer_menu: ^3.0.0
  cached_network_image: ^3.1.0
  slide_drawer: ^1.0.3
  popup_menu: ^1.0.5
  keyboard_actions: ^3.4.4
  device_info: ^2.0.2
  image_cropper: ^1.4.1
  firebase_messaging:
  country_icons: ^2.0.2
  provider: ^6.0.1
  location: ^4.3.0
  firebase_database: 
  geocoder: ^0.2.1
  google_maps_flutter: ^2.0.1
  timeago: ^3.1.0
  share_plus: ^2.1.4
  path_provider: ^2.0.0
  flutter_slidable: ^0.6.0
  swipe_to: ^0.0.1+8
  emoji_picker_flutter: ^1.0.6
  flutter_local_notifications: ^5.0.0+4
  flutter_keyboard_visibility: ^5.0.0
  emoji_picker: 
  keyboard_attachable: ^2.0.0
  show_up_animation: ^2.0.0
  rxdart: ^0.27.2
  awesome_notifications: ^0.6.17
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/chattingBottom.svg   
    - assets/svg/friendBottom.svg   
    - assets/svg/album.svg   
    - assets/svg/calender.svg   
    - assets/svg/camera.svg   
    - assets/svg/infomationBottom.svg   
    - assets/svg/profileBottom.svg   
    - assets/svg/meeting.svg
    - assets/icon/icon_kakao.png
    - assets/icon/googlelogo.jpg
    - assets/icon/wechatlogo.png
    - assets/icon/wechatlogo.jpeg
    - assets/icon/instagramlogo.jpeg
    - assets/icon/list.png
    - assets/icon/email.png
    - assets/icon/gender.png
    - assets/icon/invite.png
    - assets/icon/national.png
    - assets/icon/citizenship.png
    - assets/icon/buddy.png
    - assets/icon/questionPeson.png
    - assets/icon/location.png
    - assets/icon/chat.png
 
    - assets/icon/padlock.png
    - assets/icon/unlock.png
    - assets/icon/question.png
    - assets/icon/qa.png
    - assets/icon/groupSetting.png
    - assets/icon/updated (2).png

    - assets/icon/group.png
    - assets/icon/userSetting.png
    - assets/icon/teamwork.png
    - assets/dummy/image_4.jpg
    - assets/dummy/language.png
    - assets/dummy/passport.png
    - assets/dummy/friends.png
    - assets/image/photo_female_1.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: GloryBold
      fonts:
        - asset: assets/font/Glory-Bold.ttf
        
    - family: GlorySemi
      fonts:
        - asset: assets/font/Glory-SemiBold.ttf
          
    - family: Pathway
      fonts:
        - asset: assets/font/PathwayGothicOne-Regular.ttf
    - family: Architect
      fonts:
        - asset: assets/font/ArchitectsDaughter-Regular.ttf
        
        
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
